name: Deploy to GitHub Pages

on:
  push:
    branches: [ "gh-pages" ] 
    # Hoặc nhánh bạn muốn lắng nghe sự kiện push, ví dụ "master"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Use Node
        uses: actions/setup-node@v2
        with:
          node-version: '20' # hoặc phiên bản Node LTS bạn muốn

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages          # Nhánh sẽ chứa code build
          folder: build             # Thư mục output sau khi build
          token: ${{ secrets.GITHUB_TOKEN }}
