name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger khi push lên nhánh chính

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Hoặc phiên bản Node.js bạn sử dụng

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main  # Branch deploy
          folder: build     # Thư mục build
          # Nếu cần, sử dụng PAT để có đủ quyền:
